name: RDP Setup with Files (6 parallel sessions)

on:
  workflow_dispatch:

jobs:
  secure-rdp:
    runs-on: windows-latest
    strategy:
      matrix:
        session: [1,2,3,4,5,6]
    timeout-minutes: 3600

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Enable RDP + Firewall
        shell: powershell
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0 -Force
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 0 -Force
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "SecurityLayer" -Value 0 -Force
          netsh advfirewall firewall delete rule name='AllowRDP' >$null 2>&1
          netsh advfirewall firewall add rule name='AllowRDP' dir=in action=allow protocol=TCP localport=3389

      - name: Create RDP User
        shell: powershell
        run: |
          $cfg = "$env:TEMP\secpol.cfg"
          secedit /export /cfg $cfg
          (Get-Content $cfg) -replace 'PasswordComplexity\s*=\s*\d','PasswordComplexity = 0' | Set-Content $cfg
          secedit /configure /db $env:windir\security\local.sdb /cfg $cfg /areas SECURITYPOLICY
          gpupdate /force

          $username = "RDP${{ matrix.session }}"
          $password = "1234"
          if (Get-LocalUser -Name $username -ErrorAction SilentlyContinue) { Remove-LocalUser -Name $username }
          $securePass = ConvertTo-SecureString $password -AsPlainText -Force
          New-LocalUser -Name $username -Password $securePass -AccountNeverExpires -PasswordNeverExpires
          Add-LocalGroupMember -Group "Administrators" -Member $username
          Add-LocalGroupMember -Group "Remote Desktop Users" -Member $username

          echo "RDP_USER=$username" >> $env:GITHUB_ENV
          echo "RDP_PASS=$password" >> $env:GITHUB_ENV

      - name: Upgrade pip
        shell: powershell
        run: python -m pip install --upgrade pip

      - name: Install PyQt5
        shell: powershell
        run: pip install PyQt5

      - name: Install Playwright
        shell: powershell
        run: |
          pip install playwright
          playwright install

      - name: Install Requests
        shell: powershell
        run: pip install requests

      - name: Setup User Files
        shell: powershell
        run: |
          $username = $env:RDP_USER
          $userFolder = "C:\Users\$username\Downloads\NewFolder"
          if (-not (Test-Path $userFolder)) { New-Item -ItemType Directory -Path $userFolder -Force | Out-Null }

          $repo = "${{ github.workspace }}"
          $files = @('prox.txt','rpa.json','useragent.txt','humanex.py')
          foreach ($f in $files) {
            $src = Join-Path $repo $f
            if (Test-Path $src) { Copy-Item -Path $src -Destination $userFolder -Force }
          }

      - name: Print RDP Info
        shell: powershell
        run: |
          $username = $env:RDP_USER
          $password = $env:RDP_PASS
          $folder = "C:\Users\$username\Downloads\NewFolder"

          Write-Host '======================================'
          Write-Host ('Session: {0}' -f ${{ matrix.session }})
          Write-Host ('Username: {0}' -f $username)
          Write-Host ('Password: {0}' -f $password)
          Write-Host ('Files copied to: {0}' -f $folder)
          Write-Host 'Note: Runner is temporary — RDP session disappears when workflow finishes.'
          Write-Host '======================================'
